LogMS.Website/Controllers/AdminController.cs
using LogMS.Domain.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace LogMS.Website.Controllers
{
    public class AdminController : BaseController
    {
        public IAdminService _adminService { get; set; }

        /// <summary>
        /// 建構子
        /// </summary>
        /// <param name="adminService"></param>
        public AdminController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        /// <summary>
        /// AdminInfoPartialView
        /// </summary>
        /// <returns></returns>
        public IActionResult AdminInfoPartialView()
        {
            var result = _adminService.GetCurrentSignInAdminInfo();

            return PartialView(result.ResultData);
        }
    }
}

LogMS.Website/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace LogMS.Website.Controllers
{
    public class BaseController : Controller
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            //設定Version
            ViewBag.Version = "?" + ConfigHelper.Current.GetSection("CacheVersion").Value;
            base.OnActionExecuting(filterContext);
        }
    }
}

LogMS.Website/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace LogMS.Website.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "User");
            }

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

LogMS.Website/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace LogMS.Website.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult List()
        {
            return PartialView();
        }
    }
}

LogMS.Website/Controllers/NavController.cs
using LogMS.Domain.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LogMS.Website.Controllers
{
    public class NavController : Controller
    {
        private INavService _navService { get; set; }

        public NavController(INavService navService)
        {
            _navService = navService;
        }

        public IActionResult MenuList()
        {
            var result = _navService.ListNavData(UserAuthHelper.GetUserData().Id);

            var allmenus = result.ResultData.AllMenus;
            var currentmenus = result.ResultData.CurrentMenus;
            var levelonemenus = allmenus.Where(x => !x.ParentId.HasValue).ToList();

            ViewBag.AllMenus = allmenus;
            ViewBag.CurrentMenus = currentmenus;

            return View(levelonemenus);
        }
    }
}

LogMS.Website/Controllers/UserController.cs
using LogMS.Domain.Model.DTO;
using LogMS.Domain.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace LogMS.Website.Controllers
{
    public class UserController : BaseController
    {
        public IUserService _userService { get; set; }

        /// <summary>
        /// 建構子
        /// </summary>
        /// <param name="userService"></param>
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        /// <summary>
        /// 登入頁
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 登入
        /// </summary>
        [HttpPost]
        public IActionResult Login(UserDTO userDTO)
        {
            var model = _userService.VerifyUser(userDTO);

            if(model != null)
            {
                _userService.SignIn(model);

                //導至首頁
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// 登出
        /// </summary>
        public IActionResult SignOut()
        {
            _userService.SignOut();

            return RedirectToAction("Index", "User");
        }
    }
}

LogMS.Website/Views/Admin/AdminInfoPartialView.cshtml
@model LogMS.Domain.Model.Interface.IAdminDTO
<li class="dropdown top-menu-item-xs">
    <a href="" class="dropdown-toggle profile waves-effect waves-light" data-toggle="dropdown" aria-expanded="true"><img src="~/images/users/avatar-1.jpg" alt="user-img" class="img-circle"> </a>
    <ul class="dropdown-menu">
        <li><a><i class="ti-user m-r-10 text-custom"></i>@Model.Name</a></li>
        <li><a href="@Url.Action("SignOut","User")"><i class="ti-power-off m-r-10 text-danger"></i> 登出</a></li>
    </ul>
</li>

LogMS.Website/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

LogMS.Website/Views/Nav/MenuList.cshtml
@model IEnumerable<LogMS.Domain.Model.Interface.IMenuDTO>
@{
    IEnumerable<LogMS.Domain.Model.Interface.IMenuDTO> allmenus = ViewBag.AllMenus;
    IEnumerable<LogMS.Domain.Model.Interface.IMenuDTO> currentmenus = ViewBag.CurrentMenus;
}
<ul>
    @foreach (var menu in Model)
    {
        <li class="has_sub">
            <a href="@(string.IsNullOrEmpty(menu.Url) ? "javascript:void(0);" : menu.Url)" class="waves-effect"><i class="ti-home"></i><span>@menu.Name</span> <span class="menu-arrow"></span></a>
            @if (allmenus.Any(x => x.ParentId == menu.Id))
            {
                @await Html.PartialAsync("MenuList", allmenus.Where(x => x.ParentId == menu.Id));
            }
        </li>
    }
</ul>

LogMS.Website/Views/Shared/_GlobalScripts.cshtml
<script>
        var resizefunc = [];
</script>
<!-- jQuery  -->
<script src="@Url.Content("~/js/jquery.min.js")"></script>
<script src="@Url.Content("~/js/bootstrap.min.js")"></script>
<script src="@Url.Content("~/js/detect.js")"></script>
<script src="@Url.Content("~/js/fastclick.js")"></script>
<script src="@Url.Content("~/js/jquery.slimscroll.js")"></script>
<script src="@Url.Content("~/js/jquery.blockUI.js")"></script>
<script src="@Url.Content("~/js/waves.js")"></script>
<script src="@Url.Content("~/js/wow.min.js")"></script>
<script src="@Url.Content("~/js/jquery.nicescroll.js")"></script>
<script src="@Url.Content("~/js/jquery.scrollTo.min.js")"></script>
<script src="@Url.Content("~/js/jquery.core.js")"></script>
<script src="@Url.Content("~/js/jquery.app.js")"></script>

LogMS.Website/Views/Shared/_GlobalStyles.cshtml
<link href="@Url.Content("~/css/bootstrap.min.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/core.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/components.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/icons.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/pages.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/css/responsive.css")@ViewBag.Version" rel="stylesheet" type="text/css" />

LogMS.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Coderthemes">
    <link rel="shortcut icon" href="@Url.Content("~/images/favicon_1.ico")">
    <title>LogMS</title>
    @await Html.PartialAsync("~/Views/Shared/_GlobalStyles.cshtml")
    @RenderSection("PageStyles", false)
    <script src="@Url.Content("~//js/modernizr.min.js")"></script>
</head>
<body class="fixed-left">
    <div id="wrapper">
        <div class="topbar">
            <div class="topbar-left">
                <div class="text-center">
                    <a href="@Url.Action("Index","Home")" class="logo"><i class="icon-magnet icon-c-logo"></i><span>Sumire<i class="md md-album"></i>LogMS</span></a>
                </div>
            </div>
            <div class="navbar navbar-default" role="navigation">
                <div class="container">
                    <div class="">
                        <div class="pull-left">
                            <button class="button-menu-mobile open-left waves-effect waves-light">
                                <i class="md md-menu"></i>
                            </button>
                            <span class="clearfix"></span>
                        </div>
                        <ul class="nav navbar-nav navbar-right pull-right">
                            <li class="hidden-xs">
                                <a href="#" id="btn-fullscreen" class="waves-effect waves-light"><i class="icon-size-fullscreen"></i></a>
                            </li>
                            @Html.Action("AdminInfoPartialView", "Admin");
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="left side-menu">
            <div class="sidebar-inner slimscrollleft">
                <!--- Divider -->
                <div id="sidebar-menu">
                    @Html.Action("MenuList", "Nav");
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        @RenderBody()
    </div>
    @await Html.PartialAsync("~/Views/Shared/_GlobalScripts.cshtml")
    @RenderSection("PageScripts", false)
</body>
</html>

LogMS.Website/Views/User/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="LogMS">
    <meta name="author" content="Coderthemes">
    <link rel="shortcut icon" href="@Url.Content("~/images/favicon_1.ico")">
    <title>Log 管理系統</title>
    <link href="@Url.Content("~/css/bootstrap.min.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/css/core.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/css/components.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/css/icons.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/css/pages.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/css/responsive.css")@ViewBag.Version" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/js/modernizr.min.js")@ViewBag.Version"></script>
</head>
<body>
    <div class="account-pages"></div>
    <div class="clearfix"></div>
    <div class="wrapper-page">
        <div class=" card-box">
            <div class="panel-heading">
                <h3 class="text-center"> Sign In to <strong class="text-custom">LogMS</strong> </h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal m-t-20" action="@Url.Action("Login")" method="post">
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input name="Account" class="form-control" type="text" required="" placeholder="Account">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input name="Password" class="form-control" type="password" required="" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-group text-center m-t-40">
                        <div class="col-xs-12">
                            <button class="btn btn-pink btn-block text-uppercase waves-effect waves-light" type="submit">登入</button>
                        </div>
                    </div>
                    <div class="form-group m-t-30 m-b-0">
                        <div class="col-sm-12">
                            <a href="" class="text-dark"><i class="fa fa-lock m-r-5"></i> 忘記密碼?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-center">
                <p>還沒有帳號嗎? <a href="" class="text-primary m-l-5"><b>註冊</b></a></p>
            </div>
        </div>
    </div>

    <script src="@Url.Content("~/js/jquery.min.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/bootstrap.min.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/detect.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/fastclick.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/jquery.slimscroll.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/jquery.blockUI.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/waves.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/wow.min.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/jquery.nicescroll.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/jquery.scrollTo.min.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/jquery.core.js")@ViewBag.Version"></script>
    <script src="@Url.Content("~/js/jquery.app.js")@ViewBag.Version"></script>
</body>
</html>